Repository keras-team/keras-io, pull requests merged in 2023-11, with the labels that each got.

#1564 Implement auto-assignment for newly created issues.
  .github/workflows/auto-assignment.yaml
  .github/workflows/scripts/auto-assignment.js
Labels: keras-team-review-pending

#1562 Update about.md
  templates/about.md
Labels: keras-team-review-pending

#1573 Update image_classification_with_vision_transformer.
  examples/vision/image_classification_with_vision_transformer.py
  examples/vision/img/image_classification_with_vision_transformer/image_classification_with_vision_transformer_15_1.png
  examples/vision/img/image_classification_with_vision_transformer/image_classification_with_vision_transformer_15_2.png
  examples/vision/img/image_classification_with_vision_transformer/image_classification_with_vision_transformer_21_8.png
  examples/vision/img/image_classification_with_vision_transformer/image_classification_with_vision_transformer_21_9.png
  examples/vision/ipynb/image_classification_with_vision_transformer.ipynb
  examples/vision/md/image_classification_with_vision_transformer.md
Labels: keras-team-review-pending

#1574 Update vision/oxford_pets_image_segmentation
  examples/vision/img/oxford_pets_image_segmentation/oxford_pets_image_segmentation_16_1.jpg
  examples/vision/img/oxford_pets_image_segmentation/oxford_pets_image_segmentation_16_2.jpg
  examples/vision/img/oxford_pets_image_segmentation/oxford_pets_image_segmentation_16_2.png
  examples/vision/img/oxford_pets_image_segmentation/oxford_pets_image_segmentation_16_3.jpg
  examples/vision/img/oxford_pets_image_segmentation/oxford_pets_image_segmentation_16_3.png
  examples/vision/img/oxford_pets_image_segmentation/oxford_pets_image_segmentation_6_0.jpg
  examples/vision/img/oxford_pets_image_segmentation/oxford_pets_image_segmentation_6_1.jpg
  examples/vision/img/oxford_pets_image_segmentation/oxford_pets_image_segmentation_6_1.png
  examples/vision/ipynb/oxford_pets_image_segmentation.ipynb
  examples/vision/md/oxford_pets_image_segmentation.md
  examples/vision/oxford_pets_image_segmentation.py
Labels: keras-team-review-pending

#1576 Fix rendering issue
  examples/generative/fine_tune_via_textual_inversion.py
  examples/generative/ipynb/fine_tune_via_textual_inversion.ipynb
  examples/generative/md/fine_tune_via_textual_inversion.md
Labels: keras-team-review-pending

#1581 Update TabTransformer example for Keras 3.
  examples/structured_data/img/tabtransformer/tabtransformer_24_1.png
  examples/structured_data/img/tabtransformer/tabtransformer_24_2.png
  examples/structured_data/img/tabtransformer/tabtransformer_29_1.png
  examples/structured_data/ipynb/tabtransformer.ipynb
  examples/structured_data/md/tabtransformer.md
  examples/structured_data/tabtransformer.py
Labels: keras-team-review-pending

#1571 Add multi-backend examples/generative/text_generation_with_miniature_gpt
  examples/generative/ipynb/text_generation_with_miniature_gpt.ipynb
  examples/generative/md/text_generation_with_miniature_gpt.md
  examples/generative/text_generation_with_miniature_gpt.py
Labels: awaiting review

#1600 token_embedding fix depriciation
  guides/ipynb/keras_nlp/transformer_pretraining.ipynb
  guides/keras_nlp/transformer_pretraining.py
  guides/md/keras_nlp/transformer_pretraining.md
Labels: stat:awaiting response from contributor

#1618 Bump KerasNLP version to 0.6.3
  requirements.txt
  scripts/autogen.py
Labels: keras-team-review-pending

#1548 Simple Update in melgan_spectrogram_inversion.ipynb
  examples/audio/ipynb/melgan_spectrogram_inversion.ipynb
  examples/audio/md/melgan_spectrogram_inversion.md
  examples/audio/melgan_spectrogram_inversion.py
Labels: stat:awaiting keras-eng

#1385 Create keras_issue_template.yaml
  .github/ISSUE_TEMPLATE/keras_issue_template.yaml
Labels: stat:awaiting keras-eng

#1556 Fix import error
  examples/generative/finetune_stable_diffusion.py
  examples/generative/ipynb/finetune_stable_diffusion.ipynb
  examples/generative/md/finetune_stable_diffusion.md
Labels: stat:awaiting keras-eng
