Repository keras-team/keras-io, pull requests merged in 2023-08, with the labels that each got.

#1458 Bump KerasNLP version, update requirements
  requirements.txt
  scripts/autogen.py
Labels: keras-team-review-pending

#1465 Regenerate saving guide md and ipynb
  guides/ipynb/serialization_and_saving.ipynb
  guides/md/serialization_and_saving.md
Labels: keras-team-review-pending

#1470 Introducing Quit Flag for Unzipping Process
  examples/vision/basnet_segmentation.py
  examples/vision/img/basnet_segmentation/basnet_segmentation_10_0.png
  examples/vision/img/basnet_segmentation/basnet_segmentation_29_1.png
  examples/vision/ipynb/basnet_segmentation.ipynb
  examples/vision/md/basnet_segmentation.md
Labels: keras-team-review-pending

#1477 Update plot model files
  examples/structured_data/img/wide_deep_cross_networks/wide_deep_cross_networks_24_1.png
  examples/structured_data/img/wide_deep_cross_networks/wide_deep_cross_networks_29_1.png
  examples/structured_data/img/wide_deep_cross_networks/wide_deep_cross_networks_34_1.png
  examples/structured_data/ipynb/wide_deep_cross_networks.ipynb
  examples/structured_data/md/wide_deep_cross_networks.md
Labels: keras-team-review-pending

#1463 Change random.normal to random.uniform
  examples/generative/ipynb/wgan_gp.ipynb
  examples/generative/md/wgan_gp.md
  examples/generative/wgan_gp.py
Labels: keras-team-review-pending

#669 Updated use of embed_dim and ff_dim arguments to match expected sshap…
  examples/nlp/text_classification_with_switch_transformer.py
Labels: cla: yes, stat:awaiting response from contributor

#1488 fix formatting issue with example
  examples/nlp/ipynb/text_classification_with_switch_transformer.ipynb
  examples/nlp/md/text_classification_with_switch_transformer.md
  examples/nlp/text_classification_with_switch_transformer.py
Labels: keras-team-review-pending

#1486 Move KerasTuner, KerasCV, KerasNLP higher
  scripts/master.py
Labels: keras-team-review-pending

#1046 Fix masks in English-to-Spanish translation example
  examples/nlp/ipynb/neural_machine_translation_with_transformer.ipynb
  examples/nlp/md/neural_machine_translation_with_transformer.md
  examples/nlp/neural_machine_translation_with_transformer.py
Labels: keras-team-review-pending

#1495 Update guides_master.py for advanced saving tutorial
  scripts/guides_master.py
Labels: keras-team-review-pending

#955 Added HuggingFace links for CCT and Timeseries classification from scratch
  examples/timeseries/img/timeseries_classification_from_scratch/timeseries_classification_from_scratch_17_0.png
  examples/timeseries/img/timeseries_classification_from_scratch/timeseries_classification_from_scratch_23_0.png
  examples/timeseries/img/timeseries_classification_from_scratch/timeseries_classification_from_scratch_7_0.png
  examples/timeseries/ipynb/timeseries_classification_from_scratch.ipynb
  examples/timeseries/md/timeseries_classification_from_scratch.md
  examples/timeseries/timeseries_classification_from_scratch.py
  examples/vision/cct.py
  examples/vision/img/cct/cct_22_0.png
  examples/vision/ipynb/cct.ipynb
  examples/vision/md/cct.md
Labels: stat:awaiting response from contributor

#1496 Update KerasCV quickstart to match github
  templates/keras_cv/index.md
Labels: keras-team-review-pending

#1497 Update announcement.md
  templates/keras_core/announcement.md
Labels: keras-team-review-pending

#1509 Update keras-core version
  requirements.txt
Labels: keras-team-review-pending
